export const userTypes = {
  SET_EMAIL_LOGIN: "SET_EMAIL_LOGIN",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",

  FORGOT_EMAIL_FAIL: "FORGOT_EMAIL_FAIL",
  FORGOT_EMAIL_SUCCESS: "FORGOT_EMAIL_SUCCESS",
  SET_EMAIL_FORGOTPASSWORD: "SET_EMAIL_FORGOTPASSWORD",
  RESET_FORGOT_PASSWORD: "RESET_FORGOT_PASSWORD",
  VERIFY_OTP_SUCCESS: "VERIFY_OTP_SUCCESS",
  VERIFY_OTP_FAIL: "VERIFY_OTP_FAIL",
  FORGOT_PASSWORD_SUCCESS: "FORGOT_PASSWORD_SUCCESS",
  FORGOT_PASSWORD_FAIL: "FORGOT_PASSWORD_FAIL",
  RESET_IS_LOGIN: "RESET_IS_LOGIN",
};

export const productTypes = {
  GET_ALL_PRODUCT_SUCCESS: "GET_ALL_PRODUCT_SUCCESS",
  GET_ALL_PRODUCT_FAIL: "GET_ALL_PRODUCT_FAIL",
};


export const cartTypes = {
  SET_CART: 'SET_CART',
  SET_CITY: 'SET_CITY',
  SET_DICTRICT: 'SET_DISTRICT',
  SET_WARD: 'SET_WARD',
  PAYMENT_SUCCESS: 'PAYMENT_SUCCESS',
  PAYMENT_FAIL: 'PAYMENT_FAIL',
  RESET_PAYMENT: 'RESET_PAYMENT'
}